[advisories]
version = 2
unmaintained = "warn"
yanked = "warn"
unsound = "warn"

[licenses]
version = 2
allow = [
  "MIT",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "Unicode-DFS-2016",
  "CC0-1.0",
  "MPL-2.0",
  "OpenSSL",
]
copyleft = "warn"

[bans]
multiple-versions = "warn"
wildcards = "warn"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
