/**
 * A2A Store — per-table column whitelists for dynamic UPDATE statements.
 *
 * Extracted verbatim from `cli/src/a2a/store.js` (Aug 2026 decomposition).
 */

/**
 * Column whitelists for each table's update methods.
 * Prevents SQL column injection by rejecting unknown column names.
 * Derived from the CREATE TABLE schemas below + ALTER TABLE migrations.
 * @type {Record<string, Set<string>>}
 */
export const UPDATABLE_COLUMNS = {
  a2a_payments: new Set([
    'status',
    'sender_agent_id',
    'recipient_agent_id',
    'memo',
    'intent_id',
    'tx_hash',
    'block_number',
    'metadata',
    'updated_at',
    'completed_at',
  ]),
  a2a_payment_requests: new Set([
    'status',
    'payer_agent_id',
    'payer_address',
    'amount_paid',
    'payment_ids',
    'allow_partial',
    'metadata',
    'updated_at',
    'paid_at',
  ]),
  a2a_quotes: new Set([
    'status',
    'items',
    'subtotal',
    'fees',
    'tax',
    'total',
    'total_decimal',
    'terms',
    'estimated_delivery',
    'delivery_method',
    'fulfillment_instructions',
    'payment_id',
    'payment_request_id',
    'request_message',
    'response_message',
    'metadata',
    'expires_at',
    'quoted_at',
    'accepted_at',
    'fulfilled_at',
    'updated_at',
    'counter_count',
    'negotiation_history',
    'max_rounds',
    'escrow_id',
  ]),
  a2a_market_quotes: new Set([
    'status',
    'items',
    'subtotal',
    'fees',
    'tax',
    'total',
    'total_decimal',
    'terms',
    'estimated_delivery',
    'delivery_method',
    'fulfillment_instructions',
    'payment_id',
    'payment_request_id',
    'request_message',
    'response_message',
    'metadata',
    'expires_at',
    'quoted_at',
    'accepted_at',
    'fulfilled_at',
    'updated_at',
    'counter_count',
    'negotiation_history',
    'max_rounds',
    'escrow_id',
  ]),
  a2a_escrows: new Set([
    'status',
    'payment_id',
    'release_conditions',
    'funded_at',
    'released_at',
    'disputed_at',
    'dispute_id',
    'auto_release_after',
    'metadata',
    'intent_id',
    'updated_at',
    'expires_at',
  ]),
  a2a_disputes: new Set([
    'status',
    'resolution_type',
    'buyer_amount_decimal',
    'seller_amount_decimal',
    'resolution_note',
    'resolved_by',
    'evidence_deadline',
    'review_deadline',
    'metadata',
    'resolved_at',
  ]),
  a2a_feedback: new Set(['dimensions', 'comment', 'response', 'response_at', 'is_revoked']),
  a2a_services: new Set([
    'name',
    'description',
    'category',
    'pricing_model',
    'pricing_details',
    'active',
    'input_schema',
    'output_schema',
    'endpoint_url',
    'avg_response_time',
    'success_rate',
    'transaction_count',
    'metadata',
  ]),
  a2a_notification_log: new Set([
    'status',
    'attempts',
    'last_attempt_at',
    'last_error',
    'delivered_at',
  ]),
  a2a_subscriptions: new Set([
    'status',
    'plan_name',
    'amount',
    'amount_decimal',
    'billing_interval',
    'trial_end_date',
    'current_period_start',
    'current_period_end',
    'next_billing_date',
    'cancel_at_period_end',
    'cancelled_at',
    'past_due_since',
    'max_past_due_cycles',
    'total_billed',
    'total_billed_decimal',
    'billing_count',
    'last_payment_id',
    'metadata',
  ]),
  a2a_split_payments: new Set(['status', 'metadata', 'completed_at']),
  a2a_split_recipients: new Set([
    'recipient_address',
    'share_percent',
    'share_amount',
    'share_amount_decimal',
    'payment_id',
    'status',
  ]),
  a2a_event_subscriptions: new Set(['event_types', 'active', 'last_event_id']),
  a2a_rfqs: new Set([
    'status',
    'buyer_agent_id',
    'seller_filter',
    'max_responses',
    'deadline',
    'scoring_criteria',
    'winning_quote_id',
    'metadata',
    'updated_at',
    'awarded_at',
    'closed_at',
  ]),
  a2a_rfq_responses: new Set(['score', 'rank', 'status']),
  a2a_sla_definitions: new Set([
    'response_time_ms',
    'uptime_percent',
    'quality_min_score',
    'throughput_rps',
    'penalty_percent',
    'penalty_type',
    'active',
    'metadata',
    'updated_at',
  ]),
  a2a_sla_violations: new Set([
    'severity',
    'penalty_amount',
    'resolved',
    'metadata',
    'resolved_at',
  ]),
  a2a_workflows: new Set([
    'status',
    'total_cost',
    'current_step',
    'error',
    'metadata',
    'updated_at',
    'started_at',
    'completed_at',
  ]),
  a2a_workflow_steps: new Set([
    'status',
    'agent_address',
    'result',
    'cost',
    'error',
    'started_at',
    'completed_at',
  ]),
  agent_cards: new Set([
    'name',
    'wallet_address',
    'public_key',
    'supported_networks',
    'supported_assets',
    'a2a_skills',
    'payment_addresses',
    'endpoint_url',
    'description',
    'trust_level',
    'active',
    'suspended_at',
    'updated_at',
  ]),
  a2a_runtime_agent_cards: new Set([
    'name',
    'wallet_address',
    'public_key',
    'supported_networks',
    'supported_assets',
    'a2a_skills',
    'payment_addresses',
    'endpoint_url',
    'description',
    'trust_level',
    'active',
    'suspended_at',
    'updated_at',
  ]),
};
