# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rake/extensiontask'
require 'rspec/core/rake_task'

GEMSPEC = Gem::Specification.load('stateset_embedded.gemspec')

Rake::ExtensionTask.new('stateset_embedded', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/stateset_embedded'
end

RSpec::Core::RakeTask.new(:spec)

task default: %i[compile spec]
task test: :spec
