/* eslint-disable */
/* prettier-ignore */

/**
 * Public entry point for @stateset/embedded.
 *
 * The platform-resolution shim that napi generates lives in
 * `native-binding.js` (regenerated by `napi build --js native-binding.js`);
 * this file is hand-written and stable. It exists so every export passes
 * through `errors.js`, which turns the coded envelope the native module throws
 * into an ordinary `Error` carrying `err.code`, `err.message`, `err.details`
 * and `err.napiStatus`. See `errors.js` for the contract.
 *
 * The re-exports below are written out one per line on purpose: Node's CJS
 * named-export detection is static, and `import { Commerce } from
 * '@stateset/embedded'` only works while they stay that way. `test/error-codes.js`
 * fails if this list drifts from what the native binding exposes.
 */

const { wrapNativeExports } = require('./errors.js')

const nativeBinding = wrapNativeExports(require('./native-binding.js'))

module.exports.Commerce = nativeBinding.Commerce
module.exports.Events = nativeBinding.Events
module.exports.CommerceEventSubscription = nativeBinding.CommerceEventSubscription
module.exports.Customers = nativeBinding.Customers
module.exports.Orders = nativeBinding.Orders
module.exports.Products = nativeBinding.Products
module.exports.CustomObjects = nativeBinding.CustomObjects
module.exports.Inventory = nativeBinding.Inventory
module.exports.Returns = nativeBinding.Returns
module.exports.Payments = nativeBinding.Payments
module.exports.Shipments = nativeBinding.Shipments
module.exports.Warranties = nativeBinding.Warranties
module.exports.PurchaseOrders = nativeBinding.PurchaseOrders
module.exports.Invoices = nativeBinding.Invoices
module.exports.Bom = nativeBinding.Bom
module.exports.WorkOrders = nativeBinding.WorkOrders
module.exports.Carts = nativeBinding.Carts
module.exports.Analytics = nativeBinding.Analytics
module.exports.CurrencyOperations = nativeBinding.CurrencyOperations
module.exports.Subscriptions = nativeBinding.Subscriptions
module.exports.Promotions = nativeBinding.Promotions
module.exports.Tax = nativeBinding.Tax
module.exports.Quality = nativeBinding.Quality
module.exports.Lots = nativeBinding.Lots
module.exports.Serials = nativeBinding.Serials
module.exports.Warehouse = nativeBinding.Warehouse
module.exports.Receiving = nativeBinding.Receiving
module.exports.Fulfillment = nativeBinding.Fulfillment
module.exports.AccountsPayable = nativeBinding.AccountsPayable
module.exports.AccountsReceivable = nativeBinding.AccountsReceivable
module.exports.CostAccounting = nativeBinding.CostAccounting
module.exports.Credit = nativeBinding.Credit
module.exports.Backorders = nativeBinding.Backorders
module.exports.GeneralLedger = nativeBinding.GeneralLedger
module.exports.vesX402ComputeSigningHash = nativeBinding.vesX402ComputeSigningHash
module.exports.X402 = nativeBinding.X402
module.exports.VectorSearch = nativeBinding.VectorSearch
module.exports.jcsCanonicalize = nativeBinding.jcsCanonicalize
module.exports.domainHash = nativeBinding.domainHash
module.exports.ed25519Sign = nativeBinding.ed25519Sign
module.exports.ed25519Verify = nativeBinding.ed25519Verify
module.exports.vesHybridGenerateSigningKeypair = nativeBinding.vesHybridGenerateSigningKeypair
module.exports.vesHybridSignEventHash = nativeBinding.vesHybridSignEventHash
module.exports.vesHybridVerifyEventSignature = nativeBinding.vesHybridVerifyEventSignature
module.exports.vesTestVectorMlDsaPublicKey = nativeBinding.vesTestVectorMlDsaPublicKey
module.exports.vesHybridGenerateRecipientKeypair = nativeBinding.vesHybridGenerateRecipientKeypair
module.exports.vesTestVectorMlKemPublicKey = nativeBinding.vesTestVectorMlKemPublicKey
module.exports.vesHybridEncryptPayload = nativeBinding.vesHybridEncryptPayload
module.exports.vesHybridDecryptPayload = nativeBinding.vesHybridDecryptPayload
module.exports.vesStrictGenerateSigningKeypair = nativeBinding.vesStrictGenerateSigningKeypair
module.exports.vesStrictSignEventHash = nativeBinding.vesStrictSignEventHash
module.exports.vesStrictVerifyEventSignature = nativeBinding.vesStrictVerifyEventSignature
module.exports.vesStrictGenerateRecipientKeypair = nativeBinding.vesStrictGenerateRecipientKeypair
module.exports.vesStrictEncryptPayload = nativeBinding.vesStrictEncryptPayload
module.exports.vesStrictDecryptPayload = nativeBinding.vesStrictDecryptPayload
module.exports.vesHybridGenerateSigningPop = nativeBinding.vesHybridGenerateSigningPop
module.exports.vesHybridVerifySigningPop = nativeBinding.vesHybridVerifySigningPop
module.exports.vesStrictGenerateSigningPop = nativeBinding.vesStrictGenerateSigningPop
module.exports.vesStrictVerifySigningPop = nativeBinding.vesStrictVerifySigningPop
module.exports.aesGcmEncrypt = nativeBinding.aesGcmEncrypt
module.exports.aesGcmDecrypt = nativeBinding.aesGcmDecrypt
module.exports.merkleRoot = nativeBinding.merkleRoot
module.exports.GiftCards = nativeBinding.GiftCards
module.exports.StoreCredits = nativeBinding.StoreCredits
module.exports.Reviews = nativeBinding.Reviews
module.exports.Wishlists = nativeBinding.Wishlists
module.exports.Segments = nativeBinding.Segments
module.exports.Loyalty = nativeBinding.Loyalty
module.exports.FixedAssets = nativeBinding.FixedAssets
module.exports.RevenueRecognition = nativeBinding.RevenueRecognition
module.exports.CycleCounts = nativeBinding.CycleCounts
module.exports.EdiDocuments = nativeBinding.EdiDocuments
module.exports.Prepayments = nativeBinding.Prepayments
module.exports.VendorCredits = nativeBinding.VendorCredits
module.exports.PriceSchedules = nativeBinding.PriceSchedules
module.exports.PriceLevels = nativeBinding.PriceLevels
module.exports.TransferOrders = nativeBinding.TransferOrders
module.exports.ProductionBatches = nativeBinding.ProductionBatches
module.exports.SupplierSkus = nativeBinding.SupplierSkus
module.exports.InboundShipments = nativeBinding.InboundShipments
module.exports.ActivityLogs = nativeBinding.ActivityLogs
module.exports.Channels = nativeBinding.Channels
module.exports.Companies = nativeBinding.Companies
module.exports.UnitsOfMeasure = nativeBinding.UnitsOfMeasure
module.exports.ShippingZones = nativeBinding.ShippingZones
module.exports.StockSnapshots = nativeBinding.StockSnapshots
module.exports.PrintStations = nativeBinding.PrintStations
module.exports.IntegrationMappings = nativeBinding.IntegrationMappings
module.exports.IntegrationFieldMappings = nativeBinding.IntegrationFieldMappings
module.exports.PaymentObligations = nativeBinding.PaymentObligations
module.exports.Purgatory = nativeBinding.Purgatory
module.exports.TopologySnapshots = nativeBinding.TopologySnapshots
module.exports.VendorReturns = nativeBinding.VendorReturns
module.exports.Fraud = nativeBinding.Fraud
module.exports.SearchConfigs = nativeBinding.SearchConfigs
module.exports.Erc8004 = nativeBinding.Erc8004
module.exports.Maintenance = nativeBinding.Maintenance
