/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'stateset-embedded.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.android-arm64.node')
          } else {
            nativeBinding = require('@stateset/embedded-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'stateset-embedded.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.android-arm-eabi.node')
          } else {
            nativeBinding = require('@stateset/embedded-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'stateset-embedded.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@stateset/embedded-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'stateset-embedded.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('@stateset/embedded-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'stateset-embedded.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('@stateset/embedded-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'stateset-embedded.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./stateset-embedded.darwin-universal.node')
      } else {
        nativeBinding = require('@stateset/embedded-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'stateset-embedded.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.darwin-x64.node')
          } else {
            nativeBinding = require('@stateset/embedded-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'stateset-embedded.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.darwin-arm64.node')
          } else {
            nativeBinding = require('@stateset/embedded-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'stateset-embedded.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./stateset-embedded.freebsd-x64.node')
      } else {
        nativeBinding = require('@stateset/embedded-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-x64-musl.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'stateset-embedded.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./stateset-embedded.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('@stateset/embedded-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'stateset-embedded.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./stateset-embedded.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('@stateset/embedded-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { Commerce, Events, CommerceEventSubscription, Customers, Orders, Products, CustomObjects, Inventory, Returns, Payments, Shipments, Warranties, PurchaseOrders, Invoices, Bom, WorkOrders, Carts, Analytics, CurrencyOperations, Subscriptions, Promotions, Tax, Quality, Lots, Serials, Warehouse, Receiving, Fulfillment, AccountsPayable, AccountsReceivable, CostAccounting, Credit, Backorders, GeneralLedger, X402, VectorSearch, jcsCanonicalize, domainHash, ed25519Sign, ed25519Verify, aesGcmEncrypt, aesGcmDecrypt, merkleRoot } = nativeBinding

module.exports.Commerce = Commerce
module.exports.Events = Events
module.exports.CommerceEventSubscription = CommerceEventSubscription
module.exports.Customers = Customers
module.exports.Orders = Orders
module.exports.Products = Products
module.exports.CustomObjects = CustomObjects
module.exports.Inventory = Inventory
module.exports.Returns = Returns
module.exports.Payments = Payments
module.exports.Shipments = Shipments
module.exports.Warranties = Warranties
module.exports.PurchaseOrders = PurchaseOrders
module.exports.Invoices = Invoices
module.exports.Bom = Bom
module.exports.WorkOrders = WorkOrders
module.exports.Carts = Carts
module.exports.Analytics = Analytics
module.exports.CurrencyOperations = CurrencyOperations
module.exports.Subscriptions = Subscriptions
module.exports.Promotions = Promotions
module.exports.Tax = Tax
module.exports.Quality = Quality
module.exports.Lots = Lots
module.exports.Serials = Serials
module.exports.Warehouse = Warehouse
module.exports.Receiving = Receiving
module.exports.Fulfillment = Fulfillment
module.exports.AccountsPayable = AccountsPayable
module.exports.AccountsReceivable = AccountsReceivable
module.exports.CostAccounting = CostAccounting
module.exports.Credit = Credit
module.exports.Backorders = Backorders
module.exports.GeneralLedger = GeneralLedger
module.exports.X402 = X402
module.exports.VectorSearch = VectorSearch
module.exports.jcsCanonicalize = jcsCanonicalize
module.exports.domainHash = domainHash
module.exports.ed25519Sign = ed25519Sign
module.exports.ed25519Verify = ed25519Verify
module.exports.aesGcmEncrypt = aesGcmEncrypt
module.exports.aesGcmDecrypt = aesGcmDecrypt
module.exports.merkleRoot = merkleRoot
