/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CreateCustomerInput {
  email: string
  firstName: string
  lastName: string
  phone?: string
  acceptsMarketing?: boolean
}
export interface CustomerOutput {
  id: string
  email: string
  firstName: string
  lastName: string
  phone?: string
  status: string
  acceptsMarketing: boolean
  createdAt: string
  updatedAt: string
}
export interface CreateOrderItemInput {
  sku: string
  name: string
  quantity: number
  unitPrice: number
  productId?: string
  variantId?: string
}
export interface CreateOrderInput {
  customerId: string
  items: Array<CreateOrderItemInput>
  currency?: string
  notes?: string
}
export interface OrderItemOutput {
  id: string
  sku: string
  name: string
  quantity: number
  unitPrice: number
  total: number
}
export interface OrderOutput {
  id: string
  orderNumber: string
  customerId: string
  status: string
  totalAmount: number
  currency: string
  paymentStatus: string
  fulfillmentStatus: string
  trackingNumber?: string
  items: Array<OrderItemOutput>
  createdAt: string
  updatedAt: string
}
export interface CreateProductVariantInput {
  sku: string
  name?: string
  price: number
  compareAtPrice?: number
}
export interface CreateProductInput {
  name: string
  description?: string
  variants?: Array<CreateProductVariantInput>
}
export interface ProductOutput {
  id: string
  name: string
  slug: string
  description: string
  status: string
  createdAt: string
  updatedAt: string
}
export interface ProductVariantOutput {
  id: string
  productId: string
  sku: string
  name: string
  price: number
  compareAtPrice?: number
  isDefault: boolean
}
export interface CreateInventoryItemInput {
  sku: string
  name: string
  description?: string
  initialQuantity?: number
  reorderPoint?: number
}
export interface InventoryItemOutput {
  id: number
  sku: string
  name: string
  description?: string
  unitOfMeasure: string
  isActive: boolean
}
export interface StockLevelOutput {
  sku: string
  name: string
  totalOnHand: number
  totalAllocated: number
  totalAvailable: number
}
export interface ReservationOutput {
  id: string
  itemId: number
  quantity: number
  status: string
}
export interface CreateReturnItemInput {
  orderItemId: string
  quantity: number
}
export interface CreateReturnInput {
  orderId: string
  reason: string
  reasonDetails?: string
  items: Array<CreateReturnItemInput>
}
export interface ReturnOutput {
  id: string
  orderId: string
  status: string
  reason: string
  createdAt: string
}
export interface CreatePaymentInput {
  orderId?: string
  invoiceId?: string
  customerId?: string
  amount: number
  currency?: string
  paymentMethod?: string
}
export interface PaymentOutput {
  id: string
  paymentNumber: string
  orderId?: string
  invoiceId?: string
  customerId?: string
  amount: number
  currency: string
  status: string
  createdAt: string
  updatedAt: string
}
export interface CreateRefundInput {
  paymentId: string
  amount: number
  reason?: string
}
export interface RefundOutput {
  id: string
  refundNumber: string
  paymentId: string
  amount: number
  status: string
  reason?: string
  createdAt: string
}
export interface CreateShipmentInput {
  orderId: string
  recipientName: string
  shippingAddress: string
  carrier?: string
  shippingMethod?: string
  trackingNumber?: string
  recipientEmail?: string
  recipientPhone?: string
}
export interface ShipmentOutput {
  id: string
  shipmentNumber: string
  orderId: string
  status: string
  carrier: string
  shippingMethod: string
  trackingNumber?: string
  trackingUrl?: string
  recipientName: string
  shippingAddress: string
  createdAt: string
  updatedAt: string
}
export interface CreateWarrantyInput {
  customerId: string
  productId?: string
  orderId?: string
  warrantyType?: string
  durationMonths?: number
  serialNumber?: string
}
export interface WarrantyOutput {
  id: string
  warrantyNumber: string
  customerId: string
  productId?: string
  orderId?: string
  status: string
  warrantyType: string
  startDate: string
  endDate: string
  createdAt: string
}
export interface CreateWarrantyClaimInput {
  warrantyId: string
  issueDescription: string
  contactEmail?: string
  contactPhone?: string
}
export interface WarrantyClaimOutput {
  id: string
  claimNumber: string
  warrantyId: string
  status: string
  issueDescription: string
  resolution: string
  createdAt: string
}
export interface CreateSupplierInput {
  name: string
  supplierCode?: string
  email?: string
  phone?: string
}
export interface SupplierOutput {
  id: string
  name: string
  supplierCode?: string
  email?: string
  phone?: string
  isActive: boolean
  createdAt: string
}
export interface CreatePurchaseOrderItemInput {
  sku: string
  name: string
  quantity: number
  unitCost: number
}
export interface CreatePurchaseOrderInput {
  supplierId: string
  items: Array<CreatePurchaseOrderItemInput>
  notes?: string
}
export interface PurchaseOrderOutput {
  id: string
  poNumber: string
  supplierId: string
  status: string
  subtotal: number
  total: number
  createdAt: string
  updatedAt: string
}
export interface CreateInvoiceItemInput {
  description: string
  quantity: number
  unitPrice: number
  sku?: string
}
export interface CreateInvoiceInput {
  customerId: string
  orderId?: string
  items: Array<CreateInvoiceItemInput>
  billingEmail?: string
  billingName?: string
  notes?: string
}
export interface InvoiceOutput {
  id: string
  invoiceNumber: string
  customerId: string
  orderId?: string
  status: string
  subtotal: number
  taxAmount: number
  total: number
  amountPaid: number
  dueDate: string
  createdAt: string
  updatedAt: string
}
export interface RecordPaymentInput {
  amount: number
  paymentMethod?: string
  reference?: string
}
export interface CreateBomInput {
  name: string
  productId: string
  description?: string
  revision?: string
}
export interface BomOutput {
  id: string
  bomNumber: string
  name: string
  productId: string
  status: string
  revision: string
  createdAt: string
  updatedAt: string
}
export interface CreateBomComponentInput {
  componentSku?: string
  name: string
  quantity: number
  unitOfMeasure?: string
}
export interface BomComponentOutput {
  id: string
  bomId: string
  componentSku?: string
  name: string
  quantity: number
  unitOfMeasure: string
}
export interface CreateWorkOrderInput {
  productId: string
  bomId?: string
  quantityToBuild: number
  priority?: string
  notes?: string
}
export interface WorkOrderOutput {
  id: string
  workOrderNumber: string
  productId: string
  bomId?: string
  status: string
  priority: string
  quantityToBuild: number
  quantityCompleted: number
  createdAt: string
  updatedAt: string
}
export interface CartAddressInput {
  firstName: string
  lastName: string
  company?: string
  line1: string
  line2?: string
  city: string
  state?: string
  postalCode: string
  country: string
  phone?: string
  email?: string
}
export interface AddCartItemInput {
  productId?: string
  variantId?: string
  sku: string
  name: string
  description?: string
  imageUrl?: string
  quantity: number
  unitPrice: number
  originalPrice?: number
  weight?: number
  requiresShipping?: boolean
}
export interface CreateCartInput {
  customerId?: string
  customerEmail?: string
  customerName?: string
  currency?: string
  shippingAddress?: CartAddressInput
  billingAddress?: CartAddressInput
  notes?: string
  expiresInMinutes?: number
}
export interface UpdateCartInput {
  customerEmail?: string
  customerPhone?: string
  customerName?: string
  shippingMethod?: string
  couponCode?: string
  notes?: string
}
export interface UpdateCartItemInput {
  quantity?: number
  unitPrice?: number
}
export interface SetCartPaymentInput {
  paymentMethod: string
  paymentToken?: string
}
export interface SetCartShippingInput {
  shippingAddress: CartAddressInput
  shippingMethod?: string
  shippingCarrier?: string
  shippingAmount?: number
}
export interface CartItemOutput {
  id: string
  cartId: string
  productId?: string
  variantId?: string
  sku: string
  name: string
  description?: string
  imageUrl?: string
  quantity: number
  unitPrice: number
  originalPrice?: number
  discountAmount: number
  taxAmount: number
  total: number
  requiresShipping: boolean
  createdAt: string
  updatedAt: string
}
export interface CartAddressOutput {
  firstName: string
  lastName: string
  company?: string
  line1: string
  line2?: string
  city: string
  state?: string
  postalCode: string
  country: string
  phone?: string
  email?: string
}
export interface CartOutput {
  id: string
  cartNumber: string
  customerId?: string
  status: string
  currency: string
  subtotal: number
  taxAmount: number
  shippingAmount: number
  discountAmount: number
  grandTotal: number
  customerEmail?: string
  customerPhone?: string
  customerName?: string
  shippingAddress?: CartAddressOutput
  billingAddress?: CartAddressOutput
  billingSameAsShipping: boolean
  fulfillmentType?: string
  shippingMethod?: string
  shippingCarrier?: string
  paymentMethod?: string
  paymentStatus: string
  couponCode?: string
  orderId?: string
  orderNumber?: string
  inventoryReserved: boolean
  itemCount: number
  createdAt: string
  updatedAt: string
}
export interface CheckoutResultOutput {
  cartId: string
  orderId: string
  orderNumber: string
  paymentId?: string
  totalCharged: number
  currency: string
}
export interface ShippingRateOutput {
  id: string
  carrier: string
  service: string
  description?: string
  price: number
  currency: string
  estimatedDays?: number
}
export interface AnalyticsQueryInput {
  /**
   * Time period: today, yesterday, last7days, last30days, this_month, last_month, this_quarter,
   * last_quarter, this_year, last_year, all_time
   */
  period?: string
  /** Granularity: hour, day, week, month, quarter, year */
  granularity?: string
  /** Maximum results */
  limit?: number
}
export interface SalesSummaryOutput {
  totalRevenue: number
  orderCount: number
  averageOrderValue: number
  itemsSold: number
  uniqueCustomers: number
}
export interface RevenueByPeriodOutput {
  period: string
  revenue: number
  orderCount: number
  periodStart: string
}
export interface TopProductOutput {
  productId?: string
  sku: string
  name: string
  unitsSold: number
  revenue: number
  orderCount: number
}
export interface ProductPerformanceOutput {
  productId: string
  sku: string
  name: string
  unitsSold: number
  revenue: number
  previousUnitsSold: number
  previousRevenue: number
  unitsGrowthPercent: number
  revenueGrowthPercent: number
}
export interface CustomerMetricsOutput {
  totalCustomers: number
  newCustomers: number
  returningCustomers: number
  averageLifetimeValue: number
  averageOrdersPerCustomer: number
}
export interface TopCustomerOutput {
  customerId: string
  name: string
  email: string
  orderCount: number
  totalSpent: number
  averageOrderValue: number
}
export interface InventoryHealthOutput {
  totalSkus: number
  inStockSkus: number
  lowStockSkus: number
  outOfStockSkus: number
  totalValue: number
}
export interface LowStockItemOutput {
  sku: string
  name: string
  onHand: number
  allocated: number
  available: number
  reorderPoint?: number
  averageDailySales?: number
  daysOfStock?: number
}
export interface InventoryMovementOutput {
  sku: string
  name: string
  unitsSold: number
  unitsReceived: number
  unitsReturned: number
  unitsAdjusted: number
  netChange: number
}
export interface DemandForecastOutput {
  sku: string
  name: string
  averageDailyDemand: number
  forecastedDemand: number
  confidence: number
  currentStock: number
  daysUntilStockout?: number
  recommendedReorderQty?: number
  trend: string
}
export interface RevenueForecastOutput {
  period: string
  forecastedRevenue: number
  lowerBound: number
  upperBound: number
  confidenceLevel: number
  basedOnPeriods: number
}
export interface OrderStatusBreakdownOutput {
  pending: number
  confirmed: number
  processing: number
  shipped: number
  delivered: number
  cancelled: number
  refunded: number
}
export interface FulfillmentMetricsOutput {
  avgTimeToShipHours?: number
  avgTimeToDeliverHours?: number
  onTimeShippingPercent?: number
  onTimeDeliveryPercent?: number
  shippedToday: number
  awaitingShipment: number
}
export interface ReturnMetricsOutput {
  totalReturns: number
  returnRatePercent: number
  totalRefunded: number
}
export interface SetExchangeRateInput {
  /** Base currency code (e.g., "USD") */
  baseCurrency: string
  /** Quote currency code (e.g., "EUR") */
  quoteCurrency: string
  /** Exchange rate (e.g., 0.92 for USD to EUR) */
  rate: number
  /** Optional source of the rate (e.g., "manual", "api") */
  source?: string
}
export interface ConvertCurrencyInput {
  /** Source currency code */
  from: string
  /** Target currency code */
  to: string
  /** Amount to convert */
  amount: number
}
export interface ExchangeRateFilterInput {
  /** Filter by base currency */
  baseCurrency?: string
  /** Filter by quote currency */
  quoteCurrency?: string
}
export interface ExchangeRateOutput {
  id: string
  baseCurrency: string
  quoteCurrency: string
  rate: number
  source: string
  rateAt: string
  createdAt: string
  updatedAt: string
}
export interface ConversionResultOutput {
  originalAmount: number
  originalCurrency: string
  convertedAmount: number
  targetCurrency: string
  rate: number
  inverseRate: number
  rateAt: string
}
export interface StoreCurrencySettingsInput {
  /** Base currency for the store */
  baseCurrency: string
  /** List of enabled currency codes */
  enabledCurrencies: Array<string>
  /** Whether to auto-convert prices */
  autoConvert?: boolean
  /** Rounding mode: "half_up", "half_down", "up", "down", "half_even" */
  roundingMode?: string
}
export interface StoreCurrencySettingsOutput {
  baseCurrency: string
  enabledCurrencies: Array<string>
  autoConvert: boolean
  roundingMode: string
}
/** JavaScript-friendly Commerce instance */
export declare class Commerce {
  /**
   * Create a new Commerce instance with a database path
   * Use ":memory:" for an in-memory database
   */
  constructor(dbPath: string)
  /** Get the customers API */
  get customers(): Customers
  /** Get the orders API */
  get orders(): Orders
  /** Get the products API */
  get products(): Products
  /** Get the inventory API */
  get inventory(): Inventory
  /** Get the returns API */
  get returns(): Returns
  /** Get the payments API */
  get payments(): Payments
  /** Get the shipments API */
  get shipments(): Shipments
  /** Get the warranties API */
  get warranties(): Warranties
  /** Get the purchase orders API */
  get purchaseOrders(): PurchaseOrders
  /** Get the invoices API */
  get invoices(): Invoices
  /** Get the bill of materials API */
  get bom(): Bom
  /** Get the work orders API */
  get workOrders(): WorkOrders
  /** Get the carts/checkout API */
  get carts(): Carts
  /** Get the analytics API */
  get analytics(): Analytics
  /** Get the currency API */
  get currency(): CurrencyOperations
}
export declare class Customers {
  create(input: CreateCustomerInput): Promise<CustomerOutput>
  get(id: string): Promise<CustomerOutput | null>
  getByEmail(email: string): Promise<CustomerOutput | null>
  list(): Promise<Array<CustomerOutput>>
  count(): Promise<number>
}
export declare class Orders {
  create(input: CreateOrderInput): Promise<OrderOutput>
  get(id: string): Promise<OrderOutput | null>
  list(): Promise<Array<OrderOutput>>
  updateStatus(id: string, status: string): Promise<OrderOutput>
  ship(id: string, trackingNumber?: string | undefined | null): Promise<OrderOutput>
  cancel(id: string): Promise<OrderOutput>
  count(): Promise<number>
}
export declare class Products {
  create(input: CreateProductInput): Promise<ProductOutput>
  get(id: string): Promise<ProductOutput | null>
  getVariantBySku(sku: string): Promise<ProductVariantOutput | null>
  list(): Promise<Array<ProductOutput>>
  count(): Promise<number>
}
export declare class Inventory {
  createItem(input: CreateInventoryItemInput): Promise<InventoryItemOutput>
  getStock(sku: string): Promise<StockLevelOutput | null>
  adjust(sku: string, quantity: number, reason: string): Promise<void>
  reserve(sku: string, quantity: number, referenceType: string, referenceId: string, expiresInSeconds?: number | undefined | null): Promise<ReservationOutput>
  confirmReservation(reservationId: string): Promise<void>
  releaseReservation(reservationId: string): Promise<void>
}
export declare class Returns {
  create(input: CreateReturnInput): Promise<ReturnOutput>
  get(id: string): Promise<ReturnOutput | null>
  approve(id: string): Promise<ReturnOutput>
  reject(id: string, reason: string): Promise<ReturnOutput>
  list(): Promise<Array<ReturnOutput>>
  count(): Promise<number>
}
export declare class Payments {
  create(input: CreatePaymentInput): Promise<PaymentOutput>
  get(id: string): Promise<PaymentOutput | null>
  list(): Promise<Array<PaymentOutput>>
  markCompleted(id: string): Promise<PaymentOutput>
  markFailed(id: string, reason: string, code?: string | undefined | null): Promise<PaymentOutput>
  cancel(id: string): Promise<PaymentOutput>
  createRefund(input: CreateRefundInput): Promise<RefundOutput>
  count(): Promise<number>
}
export declare class Shipments {
  create(input: CreateShipmentInput): Promise<ShipmentOutput>
  get(id: string): Promise<ShipmentOutput | null>
  list(): Promise<Array<ShipmentOutput>>
  ship(id: string, trackingNumber?: string | undefined | null): Promise<ShipmentOutput>
  deliver(id: string): Promise<ShipmentOutput>
  cancel(id: string): Promise<ShipmentOutput>
  count(): Promise<number>
}
export declare class Warranties {
  create(input: CreateWarrantyInput): Promise<WarrantyOutput>
  get(id: string): Promise<WarrantyOutput | null>
  list(): Promise<Array<WarrantyOutput>>
  createClaim(input: CreateWarrantyClaimInput): Promise<WarrantyClaimOutput>
  approveClaim(id: string): Promise<WarrantyClaimOutput>
  denyClaim(id: string, reason: string): Promise<WarrantyClaimOutput>
  completeClaim(id: string, resolution: string): Promise<WarrantyClaimOutput>
  count(): Promise<number>
}
export declare class PurchaseOrders {
  createSupplier(input: CreateSupplierInput): Promise<SupplierOutput>
  getSupplier(id: string): Promise<SupplierOutput | null>
  listSuppliers(): Promise<Array<SupplierOutput>>
  create(input: CreatePurchaseOrderInput): Promise<PurchaseOrderOutput>
  get(id: string): Promise<PurchaseOrderOutput | null>
  list(): Promise<Array<PurchaseOrderOutput>>
  submit(id: string): Promise<PurchaseOrderOutput>
  approve(id: string, approvedBy: string): Promise<PurchaseOrderOutput>
  send(id: string): Promise<PurchaseOrderOutput>
  cancel(id: string): Promise<PurchaseOrderOutput>
  count(): Promise<number>
}
export declare class Invoices {
  create(input: CreateInvoiceInput): Promise<InvoiceOutput>
  get(id: string): Promise<InvoiceOutput | null>
  list(): Promise<Array<InvoiceOutput>>
  send(id: string): Promise<InvoiceOutput>
  void(id: string): Promise<InvoiceOutput>
  recordPayment(id: string, input: RecordPaymentInput): Promise<InvoiceOutput>
  getOverdue(): Promise<Array<InvoiceOutput>>
  count(): Promise<number>
}
export declare class Bom {
  create(input: CreateBomInput): Promise<BomOutput>
  get(id: string): Promise<BomOutput | null>
  list(): Promise<Array<BomOutput>>
  addComponent(bomId: string, input: CreateBomComponentInput): Promise<BomComponentOutput>
  getComponents(bomId: string): Promise<Array<BomComponentOutput>>
  activate(id: string): Promise<BomOutput>
  count(): Promise<number>
}
export declare class WorkOrders {
  create(input: CreateWorkOrderInput): Promise<WorkOrderOutput>
  get(id: string): Promise<WorkOrderOutput | null>
  list(): Promise<Array<WorkOrderOutput>>
  start(id: string): Promise<WorkOrderOutput>
  complete(id: string, quantityCompleted: number): Promise<WorkOrderOutput>
  cancel(id: string): Promise<WorkOrderOutput>
  count(): Promise<number>
}
export declare class Carts {
  /** Create a new cart */
  create(input: CreateCartInput): Promise<CartOutput>
  /** Get a cart by ID */
  get(id: string): Promise<CartOutput | null>
  /** Get a cart by cart number */
  getByNumber(cartNumber: string): Promise<CartOutput | null>
  /** Update a cart */
  update(id: string, input: UpdateCartInput): Promise<CartOutput>
  /** List all carts */
  list(): Promise<Array<CartOutput>>
  /** List carts for a customer */
  forCustomer(customerId: string): Promise<Array<CartOutput>>
  /** Delete a cart */
  delete(id: string): Promise<void>
  /** Add an item to the cart */
  addItem(cartId: string, item: AddCartItemInput): Promise<CartItemOutput>
  /** Update a cart item */
  updateItem(itemId: string, input: UpdateCartItemInput): Promise<CartItemOutput>
  /** Remove an item from the cart */
  removeItem(itemId: string): Promise<void>
  /** Get items in a cart */
  getItems(cartId: string): Promise<Array<CartItemOutput>>
  /** Clear all items from the cart */
  clearItems(cartId: string): Promise<void>
  /** Set the shipping address */
  setShippingAddress(id: string, address: CartAddressInput): Promise<CartOutput>
  /** Set shipping selection (address + method/carrier/amount) */
  setShipping(id: string, input: SetCartShippingInput): Promise<CartOutput>
  /** Set the billing address */
  setBillingAddress(id: string, address: CartAddressInput): Promise<CartOutput>
  /** Get available shipping rates */
  getShippingRates(id: string): Promise<Array<ShippingRateOutput>>
  /** Set payment method */
  setPayment(id: string, input: SetCartPaymentInput): Promise<CartOutput>
  /** Apply a discount/coupon code */
  applyDiscount(id: string, couponCode: string): Promise<CartOutput>
  /** Remove discount from cart */
  removeDiscount(id: string): Promise<CartOutput>
  /** Mark cart as ready for payment */
  markReadyForPayment(id: string): Promise<CartOutput>
  /** Begin checkout process */
  beginCheckout(id: string): Promise<CartOutput>
  /** Complete checkout and create order */
  complete(id: string): Promise<CheckoutResultOutput>
  /** Cancel a cart */
  cancel(id: string): Promise<CartOutput>
  /** Mark cart as abandoned */
  abandon(id: string): Promise<CartOutput>
  /** Mark cart as expired */
  expire(id: string): Promise<CartOutput>
  /** Reserve inventory for cart items */
  reserveInventory(id: string): Promise<CartOutput>
  /** Release reserved inventory for cart items */
  releaseInventory(id: string): Promise<CartOutput>
  /** Recalculate cart totals */
  recalculate(id: string): Promise<CartOutput>
  /** Set tax amount */
  setTax(id: string, taxAmount: number): Promise<CartOutput>
  /** Get abandoned carts */
  getAbandoned(): Promise<Array<CartOutput>>
  /** Get expired carts */
  getExpired(): Promise<Array<CartOutput>>
  /** Count carts */
  count(): Promise<number>
}
/** Analytics and forecasting API */
export declare class Analytics {
  /** Get sales summary for a time period */
  salesSummary(query?: AnalyticsQueryInput | undefined | null): Promise<SalesSummaryOutput>
  /** Get revenue broken down by time periods */
  revenueByPeriod(query?: AnalyticsQueryInput | undefined | null): Promise<Array<RevenueByPeriodOutput>>
  /** Get top selling products */
  topProducts(query?: AnalyticsQueryInput | undefined | null): Promise<Array<TopProductOutput>>
  /** Get product performance with period comparison */
  productPerformance(query?: AnalyticsQueryInput | undefined | null): Promise<Array<ProductPerformanceOutput>>
  /** Get customer metrics */
  customerMetrics(query?: AnalyticsQueryInput | undefined | null): Promise<CustomerMetricsOutput>
  /** Get top customers by spend */
  topCustomers(query?: AnalyticsQueryInput | undefined | null): Promise<Array<TopCustomerOutput>>
  /** Get inventory health summary */
  inventoryHealth(): Promise<InventoryHealthOutput>
  /** Get low stock items */
  lowStockItems(threshold?: number | undefined | null): Promise<Array<LowStockItemOutput>>
  /** Get inventory movement summary */
  inventoryMovement(query?: AnalyticsQueryInput | undefined | null): Promise<Array<InventoryMovementOutput>>
  /** Get demand forecast for inventory items */
  demandForecast(skus?: Array<string> | undefined | null, daysAhead?: number | undefined | null): Promise<Array<DemandForecastOutput>>
  /** Get revenue forecast */
  revenueForecast(periodsAhead?: number | undefined | null, granularity?: string | undefined | null): Promise<Array<RevenueForecastOutput>>
  /** Get order status breakdown */
  orderStatusBreakdown(query?: AnalyticsQueryInput | undefined | null): Promise<OrderStatusBreakdownOutput>
  /** Get fulfillment metrics */
  fulfillmentMetrics(query?: AnalyticsQueryInput | undefined | null): Promise<FulfillmentMetricsOutput>
  /** Get return metrics */
  returnMetrics(query?: AnalyticsQueryInput | undefined | null): Promise<ReturnMetricsOutput>
}
/** Currency and exchange rate operations API */
export declare class CurrencyOperations {
  /** Get exchange rate between two currencies */
  getRate(from: string, to: string): Promise<ExchangeRateOutput | null>
  /** Get all exchange rates for a base currency */
  getRatesFor(baseCurrency: string): Promise<Array<ExchangeRateOutput>>
  /** List exchange rates with optional filtering */
  listRates(filter?: ExchangeRateFilterInput | undefined | null): Promise<Array<ExchangeRateOutput>>
  /** Set an exchange rate */
  setRate(input: SetExchangeRateInput): Promise<ExchangeRateOutput>
  /** Set multiple exchange rates at once */
  setRates(inputs: Array<SetExchangeRateInput>): Promise<Array<ExchangeRateOutput>>
  /** Delete an exchange rate by ID */
  deleteRate(id: string): Promise<boolean>
  /** Convert an amount from one currency to another */
  convert(input: ConvertCurrencyInput): Promise<ConversionResultOutput>
  /** Get store currency settings */
  getSettings(): Promise<StoreCurrencySettingsOutput>
  /** Update store currency settings */
  updateSettings(input: StoreCurrencySettingsInput): Promise<StoreCurrencySettingsOutput>
  /** Set the store's base currency */
  setBaseCurrency(currencyCode: string): Promise<StoreCurrencySettingsOutput>
  /** Enable currencies for the store */
  enableCurrencies(currencyCodes: Array<string>): Promise<StoreCurrencySettingsOutput>
  /** Check if a currency is enabled */
  isEnabled(currencyCode: string): Promise<boolean>
  /** Get the store's base currency */
  getBaseCurrency(): Promise<string>
  /** Get all enabled currencies */
  getEnabledCurrencies(): Promise<Array<string>>
  /** Format an amount with currency symbol */
  format(amount: number, currencyCode: string): Promise<string>
}
